eureka:
  client:
    serviceUrl:
      #总服务的 地址
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9001

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #存放配置文件的git 仓库地址 SpringCloudConfig是仓库名
          uri: https://github.com/YUNZE-GH/configuration.git
#          searchPaths: /
          force-pull: true
          username: gaohan97@foxmail.com
          password: k1q235pr!
          clone-on-start: true
        default-label: main
  profiles:
    active: dev

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'