server:
  port: 9001
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties
#  security:
#    user:
#      name: admin
#      password: 123
#配置eureka信息
#eureka:
#  instance:
#    prefer-ip-address: true  # 注册服务的时候使用服务的ip地址
#  client:
#    service-url:
#      defaultZone: http://localhost:9000/eureka/