server:
  port: 8080
spring:
  application:
    name: provider
#配置eureka信息
eureka:
  instance:
    prefer-ip-address: true  # 注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/